In [59]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,2,3])
c = np.dot(a,b)
d = np.multiply(a,b)
e = a @ b
f = a * b

print(c)
print(d)
print(e)
print(f)

14
[1 4 9]
14
[1 4 9]


Numpy的矩阵乘法是dot(@)，矩阵数乘（点乘）是multiply(*)，和直觉是正好相反的

并且，array和matrix的结果并不相同：


In [66]:
a = np.matrix([[1,2],
              [4,5]])
v = np.matrix([[7],
              [8]])
print(v.shape)

(2, 1)


In [68]:
a = np.array([[1,2],
              [4,5]])
v = np.array([[7],
              [8]])
print(v.shape)

(2, 1)


In [57]:
a = np.matrix([[1,2],
               [4,5],
               [5,7]])
v = np.matrix([[7],
               [8]])
print(v.shape)

(2, 1)


In [56]:
a = np.array([[1,2],
              [4,5],
              [5,7]])
v = np.array([[7],
              [8]])
print(v.shape)

(2, 1)


In [69]:
c = np.dot(a,v) # 向量点积或矩阵乘法，shape不合法时报错
print(c)
d = np.multiply(a,v) # 先广播后对位相乘，shape无法广播时报错
print(d)
e = a@v # 向量点积或矩阵乘法，shape不合法时报错
print(e)
f = a*v # array：先广播后对位相乘；matrix：矩阵乘法，shape不合法时报错
print(f)



[[23]
 [68]]
[[ 7 14]
 [32 40]]
[[23]
 [68]]
[[ 7 14]
 [32 40]]


https://numpy.org/doc/stable/reference/generated/numpy.dot.html

https://blog.csdn.net/zenghaitao0128/article/details/78715140